import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { ExportRow } from "@/lib/types";

/**
 * A clean PDF report: one summary header + one block per opportunity.
 * pdf-lib has no table primitive, so we lay out labelled blocks (robust + readable).
 */
export async function toPdf(rows: ExportRow[], title = "LEADer — Opportunity report"): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const margin = 48;
  const pageW = 595.28; // A4
  const pageH = 841.89;
  let page = doc.addPage([pageW, pageH]);
  let y = pageH - margin;

  const ink = rgb(0.09, 0.1, 0.13);
  const muted = rgb(0.42, 0.45, 0.5);
  const accent = rgb(0.23, 0.51, 0.96);

  const newPageIfNeeded = (needed: number) => {
    if (y - needed < margin) {
      page = doc.addPage([pageW, pageH]);
      y = pageH - margin;
    }
  };

  const wrap = (text: string, size: number, maxW: number, f = font): string[] => {
    const words = (text || "").replace(/\n/g, " ").split(/\s+/).filter(Boolean);
    const lines: string[] = [];
    let line = "";
    for (const w of words) {
      const test = line ? `${line} ${w}` : w;
      if (f.widthOfTextAtSize(test, size) > maxW) {
        if (line) lines.push(line);
        line = w;
      } else line = test;
    }
    if (line) lines.push(line);
    return lines.length ? lines : [""];
  };

  // Header
  page.drawText(title, { x: margin, y, size: 18, font: bold, color: ink });
  y -= 22;
  page.drawText(
    `${rows.length} opportunit${rows.length === 1 ? "y" : "ies"} · generated by LEADer`,
    { x: margin, y, size: 10, font, color: muted },
  );
  y -= 24;

  const contentW = pageW - margin * 2;

  rows.forEach((r, i) => {
    newPageIfNeeded(90);
    page.drawLine({
      start: { x: margin, y },
      end: { x: pageW - margin, y },
      thickness: 0.5,
      color: rgb(0.85, 0.86, 0.88),
    });
    y -= 18;

    // Title + score badge
    const titleLines = wrap(`${i + 1}. ${r.Title}`, 12, contentW - 60, bold);
    titleLines.forEach((ln) => {
      newPageIfNeeded(16);
      page.drawText(ln, { x: margin, y, size: 12, font: bold, color: ink });
      y -= 15;
    });
    page.drawText(`Score: ${r["Match score"]}`, {
      x: pageW - margin - 70,
      y: y + 15,
      size: 10,
      font: bold,
      color: accent,
    });

    const meta = `${r.Source}  ·  ${r.Budget}  ·  Deadline: ${r.Deadline}  ·  ${r.Status}`;
    page.drawText(meta, { x: margin, y, size: 9, font, color: muted });
    y -= 14;

    if (r.Summary) {
      wrap(r.Summary, 9.5, contentW).forEach((ln) => {
        newPageIfNeeded(13);
        page.drawText(ln, { x: margin, y, size: 9.5, font, color: ink });
        y -= 12;
      });
    }
    if (r["Next action"]) {
      newPageIfNeeded(13);
      page.drawText(`Next: ${r["Next action"]}`, { x: margin, y, size: 9, font: bold, color: ink });
      y -= 12;
    }
    if (r.URL) {
      newPageIfNeeded(13);
      page.drawText(r.URL, { x: margin, y, size: 8.5, font, color: accent });
      y -= 12;
    }
    y -= 6;
  });

  const bytes = await doc.save();
  return Buffer.from(bytes);
}
